# Branch Protection Config for standard/ default branches 
# Each repo can be overwritten as needed in repo settings or modifying the repo-config file
# Snake case used because GitHub API fields are in that case
# https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection 

# Default branch protection 
branch_protection:
  required_status_checks: null # Required field set to null when not using status checks
    # strict: false # branch up to date
    # contexts: []
    # checks: []
  required_pull_request_reviews:
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
    require_last_push_approval: false
    required_approving_review_count: 1
    bypass_pull_request_allowances:
      users:
      - MOvenshire
  restrictions: # Required field for push access 
    users:
    - ant-man21
  required_signatures: true
  enforce_admins: false
  required_linear_history: true
  allow_force_pushes: false 
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: false
  lock_branch: false


# Branch Protection Config for locked branches (only required fields)
lock_branch_protection:
  required_status_checks: null # Required field null or obj 
  required_pull_request_reviews:
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
    require_last_push_approval: false
    required_approving_review_count: 2
    bypass_pull_request_allowances:
      users:
      - MOvenshire
  restrictions: null # Required field for push access
  lock_branch: true
  enforce_admins: true
